"use client";
import { useState, useEffect, lazy, Suspense } from 'react';
import { flushSync } from 'react-dom';

const World = lazy(() => import('./world'));
const chapters = [
 { era:'DEEP TIME', short:'An ancient world', title:'Small life.\nEnormous stakes.', text:'Billions of years before humans, Earth was a microbial world. Viruses called bacteriophages invade bacteria, delivering DNA that can turn a cell into a virus factory.', action:'Launch the invasion', result:'The phage delivers its DNA into the bacterium. Some infections end with the cell bursting, releasing a new generation of viruses.', takeaway:'The struggle between microbes and viruses helped shape the living world.', labels:['Bacterium','Bacteriophage','Viral DNA'], details:['A living cell with its own DNA and protein-making machinery.','A virus that infects bacteria. Its head holds genetic material; its tail helps deliver it.','Instructions that can redirect a bacterium to produce more viruses.'], note:'An illustrative ancient setting. We do not know exactly when phages or restriction systems first evolved.' },
 { era:'EVOLUTION', short:'Molecular defence', title:'A cut that\nchanges everything.', text:'Some bacteria evolved restriction enzymes: proteins that recognise particular DNA sequences and cut there. Paired chemical marking systems help protect the bacterium’s own DNA.', action:'Activate the defence', result:'The enzyme cuts unprotected invading DNA at a matching sequence. This can interrupt infection. It is one defence among many—not an unbeatable shield.', takeaway:'Evolution produced a precise molecular tool without planning its future use.', labels:['Restriction enzyme','Invading DNA','Protected host DNA'], details:['A folded protein, not literal scissors. Its shape and chemistry let it recognise and cut certain DNA sequences.','Foreign DNA can be vulnerable if it lacks the protective markings for this restriction system.','Matching chemical marks, often methyl groups, help prevent the cell’s own DNA from being cut.'], note:'Molecular shapes, motion and colours are simplified. This scene is not to scale.' },
 { era:'NATURE’S TOOLKIT', short:'Portable instructions', title:'A little ring.\nA useful extra.', text:'Plasmids are DNA molecules separate from a cell’s main chromosome. Often small rings, they can copy themselves. Some pass between cells, carrying genes that help their hosts survive.', action:'Copy the plasmid', result:'A second plasmid appears. Plasmids have their own replication instructions, but rely on the host cell’s machinery to make copies.', takeaway:'Scientists adapted naturally occurring plasmids into carriers for new genes.', labels:['Plasmid','Main chromosome','Host cell'], details:['An extra DNA molecule. Humans did not invent plasmids; their evolutionary origins are complex.','The bacterium’s main collection of genetic instructions. The plasmid is separate from it.','The cell supplies the resources and machinery that keep the plasmid going.'], note:'Not every bacterium carries a plasmid. Not every plasmid is circular or transferable.' },
 { era:'1973', short:'Cut. Join. Carry.', title:'Nature’s tools.\nA new combination.', text:'In the 1960s and early 1970s, researchers uncovered predictable DNA-cutting enzymes. In 1973, Cohen, Boyer and colleagues joined DNA fragments into plasmids that could function inside bacteria.', action:'Join a new DNA segment', result:'A new segment becomes part of the plasmid. Restriction enzymes make compatible cuts and DNA ligase seals the joins. Bacteria can then copy the engineered plasmid.', takeaway:'DNA from different sources could be combined and maintained inside a living cell.', labels:['Plasmid carrier','New DNA segment','Joined DNA'], details:['Also called a vector: it brings a chosen DNA segment into a host cell.','A chosen set of instructions. Carrying a gene and successfully expressing it are different steps.','DNA ligase seals the backbone. The resulting combination is called recombinant DNA.'], note:'A conceptual reconstruction of the principle, not a laboratory protocol.' },
 { era:'1977', short:'Read the recipe', title:'Different species.\nA shared language.', text:'Life uses an almost universal genetic code. With suitably designed instructions and control signals, bacteria can produce a human protein. In 1977, researchers demonstrated this with the hormone somatostatin.', action:'Make a protein', result:'The cell copies DNA instructions into a temporary RNA message. A ribosome reads the message and links amino acids into a protein.', takeaway:'A bacterium does not become human. Its machinery follows a new recipe.', labels:['DNA instructions','RNA message','Ribosome'], details:['The gene is the recipe. It also needs control signals that the bacterial cell can use.','A temporary working copy carries instructions from DNA to the protein-making machinery.','A molecular machine that reads the message and assembles a chain of amino acids.'], note:'Bacteria cannot make every human protein correctly. Folding and chemical modifications can matter.' },
 { era:'1978 → 1982', short:'The insulin moment', title:'A microscopic\nlife-saver.', text:'Insulin helps regulate blood sugar. In 1978, scientists used engineered bacteria to produce its two chains, then combined them into working human insulin. In 1982, recombinant human insulin received FDA approval.', action:'Assemble the insulin', result:'The two chains come together, connected by chemical bridges. This shows the early two-chain approach; many modern methods start with an insulin precursor.', takeaway:'An engineered microbe could help supply a medicine essential for people with type 1 diabetes.', labels:['A chain','B chain','Insulin'], details:['One of the two amino-acid chains in insulin.','The other chain. In the early method, the chains were produced separately and processed before joining.','A hormone, not a cure for diabetes. Purified replacement insulin helps people manage blood sugar and survive.'], note:'A simplified chain diagram, not an atomically accurate insulin structure.' },
 { era:'TODAY', short:'Science becomes care', title:'From survival\nto saving lives.', text:'Engineered bacteria and yeast can produce insulin in controlled fermentation tanks. The product is recovered, purified and tested before becoming medicine. Other engineered cells help make many more biological medicines.', action:'Follow the production', result:'Cells grow → protein is produced → the product is purified → quality is tested. Patients receive the medicine, not the production bacteria.', takeaway:'Evolution supplied the parts. Human curiosity connected them to a new purpose.', labels:['Engineered cells','Production vessel','Purified medicine'], details:['Living cells use nutrients and energy to build the desired protein.','A controlled environment supports production at scale.','Purification and quality testing are crucial steps between a growing culture and a medicine.'], note:'A simplified overview of production. Medicine is purified and tested before use.' }
];
export default function Home(){
 const [step,setStep]=useState(0),[active,setActive]=useState(false),[focus,setFocus]=useState(0),[paused,setPaused]=useState(false),[replay,setReplay]=useState(0);const c=chapters[step];
 const go=(n:number)=>{setStep(n);setActive(false);setFocus(0)};
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'explore_genetic_engineering',description:'Open one of seven science chapters and optionally reveal its process. Chapters: 1 phages, 2 restriction enzymes, 3 plasmids, 4 recombinant DNA, 5 expression, 6 insulin, 7 factories.',inputSchema:{type:'object',properties:{chapter:{type:'integer',minimum:1,maximum:7},reveal:{type:'boolean'}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const v=input as {chapter:number;reveal?:boolean};if(!v||!Number.isInteger(v.chapter)||v.chapter<1||v.chapter>7||(v.reveal!==undefined&&typeof v.reveal!=='boolean'))throw new Error('Choose chapter 1–7 and an optional boolean reveal.');flushSync(()=>{setStep(v.chapter-1);setFocus(0);setActive(v.reveal??false)});return {chapter:v.chapter,title:chapters[v.chapter-1].short,revealed:v.reveal??false}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 return <main><header><a className="brand" href={import.meta.env.BASE_URL}><span className="brandmark">✳</span> LIFE, REWRITTEN</a><span className="header-note">AN INTERACTIVE HISTORY OF GENETIC ENGINEERING</span><span className="chapter-count">0{step+1} <span>/ 07</span></span></header>
 <nav className="timeline" aria-label="Timeline chapters">{chapters.map((ch,i)=><button key={ch.era} className={step===i?'selected':''} aria-current={step===i?'step':undefined} onClick={()=>go(i)}><span className="rail-dot"/><span className="time-era">{ch.era}</span><span>{ch.short}</span></button>)}</nav>
 <section className="experience" aria-label="Interactive science chapter"><article className="story" key={step}><div className="eyebrow"><span/> {c.era}</div><h1>{c.title.split('\n').map((line,i)=><span key={line} className={i?'accent':''}>{line}</span>)}</h1><p className="intro">{c.text}</p><button className="action" onClick={()=>{setActive(true);setPaused(false);setReplay(n=>n+1)}}>{active?'↺ Replay animation':c.action}<span>{active?'':'▷'}</span></button><div className="discovery" aria-live="polite"><span>{active?'HOW IT WORKS':'THE BIG IDEA'}</span><p>{active?c.result:c.takeaway}</p></div></article>
 <div className="scene"><div className="scene-top"><span><i/> LIVE 3D EXPLORATION</span><button onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?'▷ Resume motion':'Ⅱ Pause motion'}</button></div><Suspense fallback={<div className="loading">Entering the microscopic world…</div>}><World step={step} active={active} focus={focus} paused={paused} replay={replay}/></Suspense><div className="scene-footer"><span>DRAG TO ORBIT · SCROLL TO ZOOM</span><span>ILLUSTRATIVE · NOT TO SCALE</span></div></div></section>
 <section className="inspect" aria-label="Explore the parts"><div className="inspect-label">LOOK CLOSER<span>Choose a part to explore</span></div><div className="part-buttons">{c.labels.map((label,i)=><button key={label} aria-pressed={focus===i} onClick={()=>setFocus(i)}><span>0{i+1}</span>{label}</button>)}</div><p aria-live="polite">{c.details[focus]}</p></section>
 <footer><span>{c.note}</span><div><button disabled={step===0} onClick={()=>go(step-1)}>← Back</button><button className="next" onClick={()=>go(step===6?0:step+1)}>{step===6?'Explore again':'Next chapter'} →</button></div></footer>
 <details className="sources"><summary>The science behind the story</summary><p>Ancient scenes are reconstructions; no precise origin date is claimed for restriction enzymes or plasmids. The dated milestones are documented discoveries.</p><div><a href="https://www.nobelprize.org/uploads/2018/06/smith-lecture.pdf" target="_blank" rel="noreferrer">Restriction enzymes · Nobel lecture ↗</a><a href="https://www.genome.gov/genetics-glossary/Plasmid" target="_blank" rel="noreferrer">Plasmids · NHGRI ↗</a><a href="https://pubmed.ncbi.nlm.nih.gov/4594039/" target="_blank" rel="noreferrer">Recombinant plasmids · 1973 paper ↗</a><a href="https://www.gene.com/stories/the-paper" target="_blank" rel="noreferrer">Somatostatin · 1977 milestone ↗</a><a href="https://www.fda.gov/about-fda/fda-history-exhibits/100-years-insulin" target="_blank" rel="noreferrer">Human insulin · FDA history ↗</a></div></details></main>
}

