"use client";
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
export default function World({step,active,focus,paused,replay}:{step:number;active:boolean;focus:number;paused:boolean;replay:number}){
 const playback=useRef({active,paused,replay});playback.current={active,paused,replay};
 const [caption,setCaption]=useState('Press the chapter button to play');
 const host=useRef<HTMLDivElement>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{
  if(!host.current)return;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{setFailed(true);return}
  const el=host.current;setFailed(false);renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(0,1.2,10.5);
  const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=5;controls.maxDistance=16;controls.autoRotate=!paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.autoRotateSpeed=.45;
  renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','3D model: drag to orbit, or use arrow keys. Plus and minus zoom.');
  const onKey=(e:KeyboardEvent)=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key))return;e.preventDefault();const s=new THREE.Spherical().setFromVector3(camera.position);if(e.key==='ArrowLeft')s.theta-=.15;if(e.key==='ArrowRight')s.theta+=.15;if(e.key==='ArrowUp')s.phi-=.15;if(e.key==='ArrowDown')s.phi+=.15;if(e.key==='+'||e.key==='=')s.radius=Math.max(5,s.radius-.5);if(e.key==='-')s.radius=Math.min(16,s.radius+.5);s.makeSafe();camera.position.setFromSpherical(s);controls.update()};renderer.domElement.addEventListener('keydown',onKey);
  scene.add(new THREE.AmbientLight(0x82c4bd,1.6));const light=new THREE.DirectionalLight(0xe5fff0,3);light.position.set(3,5,4);scene.add(light);const rim=new THREE.PointLight(0x59e8ba,24);rim.position.set(-3,-1,2);scene.add(rim);
  const group=new THREE.Group();scene.add(group);const green=0xbaf69c,teal=0x56c9bb,red=0xf5888a,gold=0xf4c97b;
  const material=(color:number,opacity=1)=>new THREE.MeshStandardMaterial({color,roughness:.32,metalness:.15,transparent:opacity<1,opacity,depthWrite:opacity===1});
  const ball=(parent:THREE.Object3D,x:number,y:number,z:number,r:number,color:number)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(r,20,14),material(color));o.position.set(x,y,z);parent.add(o);return o};
  const tube=(parent:THREE.Object3D,pts:THREE.Vector3[],r:number,color:number)=>{const o=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),Math.max(30,pts.length*3),r,8,false),material(color));parent.add(o);return o};
  const line=(parent:THREE.Object3D,a:THREE.Vector3,b:THREE.Vector3,r:number,color:number)=>tube(parent,[a,b],r,color);
  const ring=(parent:THREE.Object3D,r:number,color:number,start=0,end=Math.PI*2)=>{const pts=Array.from({length:100},(_,i)=>{const t=start+(end-start)*i/99;return new THREE.Vector3(Math.cos(t)*r,Math.sin(t)*r,Math.sin(t*3)*.09)});return tube(parent,pts,.055,color)};
  const dna=(parent:THREE.Object3D,length:number,color:number,offset=0)=>{for(let strand=0;strand<2;strand++){const pts=Array.from({length:100},(_,i)=>{const t=i/99*length;return new THREE.Vector3(t-length/2,Math.sin(t*4+strand*Math.PI)*.18+offset,Math.cos(t*4+strand*Math.PI)*.18)});tube(parent,pts,.032,color)}for(let i=0;i<length*9;i++){const x=i/9;line(parent,new THREE.Vector3(x-length/2,Math.sin(x*4)*.18+offset,Math.cos(x*4)*.18),new THREE.Vector3(x-length/2,-Math.sin(x*4)*.18+offset,-Math.cos(x*4)*.18),.016,0xacc0b3)}};
  const cell=(parent:THREE.Object3D,x=0,y=0,z=0,scale=1)=>{const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(scale);const shell=new THREE.Mesh(new THREE.CapsuleGeometry(.8,1.8,12,40),material(focus===0?teal:0x428b89,.23));shell.rotation.z=Math.PI/2;g.add(shell);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(shell.geometry,20),new THREE.LineBasicMaterial({color:teal,transparent:true,opacity:.13}));edge.rotation.copy(shell.rotation);g.add(edge);const pts=Array.from({length:100},(_,i)=>{const t=i/99*Math.PI*8;return new THREE.Vector3(Math.sin(t)*.8,Math.cos(t*2)*.32,Math.sin(t*3)*.3)});tube(g,pts,.025,teal);for(let i=0;i<22;i++)ball(g,Math.sin(i*2.4)*1.2,Math.cos(i*5)*.4,Math.sin(i*3)*.4,.035,green);parent.add(g);return g};
  const phage=(parent:THREE.Object3D,x:number,y:number,z:number)=>{const g=new THREE.Group();g.position.set(x,y,z);const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.35,1),material(red));head.position.y=.75;g.add(head);const wire=new THREE.LineSegments(new THREE.EdgesGeometry(head.geometry),new THREE.LineBasicMaterial({color:0xffc0a7}));wire.position.y=.75;g.add(wire);line(g,new THREE.Vector3(0,.45,0),new THREE.Vector3(0,-.1,0),.06,gold);for(let i=0;i<6;i++){const t=i/6*Math.PI*2;tube(g,[new THREE.Vector3(0,0,0),new THREE.Vector3(Math.cos(t)*.3,-.16,Math.sin(t)*.3),new THREE.Vector3(Math.cos(t)*.46,-.5,Math.sin(t)*.46)],.025,red)}parent.add(g);return g};
  const ease=(t:number,a:number,b:number)=>{const x=Math.max(0,Math.min(1,(t-a)/(b-a)));return x*x*(3-2*x)};
  let animate=(t:number)=>{};
  const phases=[['Approach','Attach to the cell','Inject viral DNA','Viral instructions are inside'],['Recognise a matching sequence','Bind the DNA','Cut both strands','Fragments separate'],['Copy the DNA ring','Complete a new copy','Separate the copies','Two plasmids remain'],['Align the new segment','Fit compatible ends','Seal the joins','A recombinant plasmid'],['Copy a message from DNA','Read the RNA message','Build an amino-acid chain','A protein has been made'],['Bring the chains together','Align the chains','Form chemical bridges','Assembled insulin'],['Cells produce protein','Recover the product','Purify and test','Medicine, without the bacteria']];
  if(step===0){cell(group,0,-.65,0,1.15);const virus=phage(group,.2,1.5,0);phage(group,-2.1,1,-1);phage(group,2,1.4,-1.5);const payload=new THREE.Group();dna(payload,1.4,red);payload.rotation.z=Math.PI/2;group.add(payload);animate=t=>{virus.position.y=1.5-.73*ease(t,0,2);payload.visible=t>3;payload.scale.setScalar(.03+.97*ease(t,3,6.5));payload.position.set(.2,.65-1.15*ease(t,3,6.5),.05)}}
  if(step===1){const left=new THREE.Group(),right=new THREE.Group(),enzyme=new THREE.Group();dna(left,2.4,red);dna(right,2.4,red);group.add(left,right,enzyme);for(let i=0;i<9;i++)ball(enzyme,Math.sin(i*2)*.45,Math.cos(i*2)*.35,.15+Math.sin(i)*.23,.3,green);const hostDNA=new THREE.Group();dna(hostDNA,3,teal);hostDNA.position.y=-1.45;group.add(hostDNA);for(let i=0;i<7;i++)ball(hostDNA,-1.3+i*.4,.27,0,.085,gold);animate=t=>{enzyme.position.set(-1.5*(1-ease(t,0,2)),1.1*(1-ease(t,1.5,3)),0);const cut=ease(t,4,6.5);left.position.x=-1.2-.55*cut;right.position.x=1.2+.55*cut;left.rotation.z=.1*cut;right.rotation.z=-.14*cut;enzyme.position.y+=.7*ease(t,5,7)}}
  if(step===2){cell(group,0,0,-.2,1.25);const p=new THREE.Group(),copy=new THREE.Group();ring(p,.5,green);const strand=ring(copy,.5,gold);p.position.set(.65,.1,.85);group.add(p,copy);animate=t=>{copy.visible=t>0;strand.geometry.setDrawRange(0,Math.floor(strand.geometry.index!.count*ease(t,0,4)/3)*3);copy.position.set(.65-1.25*ease(t,4,7),.1,.85+.12*Math.sin(ease(t,0,7)*Math.PI))}}
  if(step===3){ring(group,1.5,teal,.65,Math.PI*2-.65);const piece=new THREE.Group();ring(piece,1.5,gold,-.65,.65);group.add(piece);const joins=[-.65,.65].map(t=>ball(group,Math.cos(t)*1.5,Math.sin(t)*1.5,Math.sin(t*3)*.09,.11,green));animate=t=>{piece.position.x=1.15*(1-ease(t,0,4));joins.forEach((j,i)=>{j.visible=t>4+i*.7;j.scale.setScalar(.1+.9*ease(t,4+i*.7,5.5+i*.7))})}}
  if(step===4){const g=new THREE.Group();dna(g,4.3,teal);g.position.y=1.45;group.add(g);const message=tube(group,[new THREE.Vector3(-1.8,1,0),new THREE.Vector3(-1,.15,0),new THREE.Vector3(.5,-.2,0),new THREE.Vector3(2,-.1,0)],.045,gold);const ribosome=new THREE.Group();ball(ribosome,0,.2,0,.5,green);ball(ribosome,0,-.3,0,.35,teal);group.add(ribosome);const chain=Array.from({length:22},(_,i)=>ball(ribosome,i*.07,-.65-i*.04,Math.sin(i*.8)*.23,.075,i%2?green:gold));animate=t=>{message.geometry.setDrawRange(0,Math.floor(message.geometry.index!.count*ease(t,0,2)/3)*3);ribosome.visible=t>=2;ribosome.position.set(-.7+2.1*ease(t,2,7),-.1,0);chain.forEach((b,i)=>{b.visible=t>=2.5+i*.2})}}
  if(step===5){const chains=[new THREE.Group(),new THREE.Group()];chains.forEach((g,chain)=>{group.add(g);const pts:THREE.Vector3[]=[];for(let i=0;i<(chain?30:21);i++){const a=i*.55,p=new THREE.Vector3(Math.cos(a)*.6,i*.07-.9,Math.sin(a)*.6);pts.push(p);ball(g,p.x,p.y,p.z,.095,chain?gold:green)}tube(g,pts,.035,chain?gold:green)});const links=[-.6,.35].map(y=>line(group,new THREE.Vector3(-.3,y,.3),new THREE.Vector3(.5,y,.3),.035,teal));animate=t=>{chains.forEach((g,i)=>g.position.x=(i?1:-1)*(1.05-.65*ease(t,0,4)));links.forEach((l,i)=>{l.visible=t>4+i;l.scale.x=ease(t,4+i,5+i)})}}
  if(step===6){const vessel=new THREE.Mesh(new THREE.CylinderGeometry(1.3,1.3,3.3,48,1,true),material(teal,.14));group.add(vessel);for(const y of [-1.65,1.65]){const r=new THREE.Mesh(new THREE.TorusGeometry(1.3,.06,12,60),material(teal));r.rotation.x=Math.PI/2;r.position.y=y;group.add(r)}for(let i=0;i<9;i++)cell(group,Math.sin(i*5)*.65,(i%3-1)*.85,Math.cos(i*3)*.65,.22);const proteins=Array.from({length:8},(_,i)=>ball(group,0,0,0,.07,gold));const vial=new THREE.Mesh(new THREE.CylinderGeometry(.3,.3,.9,24),material(0xd7f7e5,.5));vial.position.set(2.6,-.5,0);group.add(vial);const product=ball(group,2.6,-.5,0,.16,green);animate=t=>{proteins.forEach((p,i)=>{const f=ease(t,i*.15,5+i*.15);p.visible=t>i*.15&&f<1;p.position.set(.1+2.5*f,Math.sin(i*2)*.6*(1-f)-.5*f,.4*Math.cos(i)*(1-f))});product.visible=t>6;product.scale.setScalar(ease(t,6,7))}}
  const positions=new Float32Array(240*3);for(let i=0;i<240;i++){positions[i*3]=Math.sin(i*48.3)*10;positions[i*3+1]=Math.cos(i*12.7)*7;positions[i*3+2]=-4+Math.sin(i*7.1)*4}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));scene.add(new THREE.Points(geo,new THREE.PointsMaterial({color:0x83c0ac,size:.018,transparent:true,opacity:.5})));
  group.rotation.set(.12,-.2,-.08);group.scale.setScalar(focus===1?1.06:1);
  const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0,elapsed=0,last=performance.now(),version=playback.current.replay,lastCaption='';const render=()=>{const now=performance.now(),state=playback.current;if(version!==state.replay){elapsed=0;version=state.replay}if(state.active&&!state.paused)elapsed=Math.min(8,elapsed+Math.min((now-last)/1000,.1));if(!state.active)elapsed=0;last=now;animate(elapsed);controls.autoRotate=!state.active&&!state.paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches;const text=state.active?phases[step][Math.min(3,Math.floor(elapsed/2))]:'Press the chapter button to play';if(text!==lastCaption){lastCaption=text;setCaption(text)}controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(render)};render();
  return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments||o instanceof THREE.Points){o.geometry.dispose();const m=Array.isArray(o.material)?o.material:[o.material];m.forEach(x=>x.dispose())}});renderer.dispose();renderer.domElement.remove()};
 },[step]);
 return <><div ref={host} className="world" role="img" aria-label="Rotatable 3D scientific illustration. Use the chapter action and labelled parts to explore.">{failed&&<p className="fallback">Your browser could not start 3D graphics. You can still explore every chapter using the explanations and controls.</p>}</div>{!failed&&<div className="animation-caption" aria-live="polite">{paused&&active?'Paused · ':''}{caption}</div>}</>
}
